// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Q0kg6UodEEBUV12VjCoXmiDJEmyVIBY',
    appId: '1:502143416877:web:87e97f899ee66f11ab96a4',
    messagingSenderId: '502143416877',
    projectId: 'travel-guide-7908f',
    authDomain: 'travel-guide-7908f.firebaseapp.com',
    storageBucket: 'travel-guide-7908f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAF3YhOsNySHH9fJtcd_wL9BdyTaIXQI',
    appId: '1:502143416877:android:12b0052935c97eedab96a4',
    messagingSenderId: '502143416877',
    projectId: 'travel-guide-7908f',
    storageBucket: 'travel-guide-7908f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB050T6z737m988kKkVOKaW0JuHwVeM24c',
    appId: '1:502143416877:ios:b4784af4c16da219ab96a4',
    messagingSenderId: '502143416877',
    projectId: 'travel-guide-7908f',
    storageBucket: 'travel-guide-7908f.appspot.com',
    iosBundleId: 'com.example.travelGuide',
  );
}
